" Do not use compatibility mode
set nocompatible
filetype off

" Use utf-8
set encoding=utf-8

" Enable mouse
set mouse=a

" Set line numbers
set number

" Better indent
set autoindent
set smartindent

" Better search
set ignorecase
set smartcase
set incsearch
set magic

" Set history to 2,048 commands
set history=2048

" Fix backspace
set backspace=eol,start,indent
set colorcolumn=79,80

" No backups
set nobackup
set nowb
set noswapfile

" Tab behavior
set expandtab
set smarttab
set shiftwidth=3
set tabstop=3

" Never show mode
set noshowmode

" Python folding
set foldmethod=indent
set foldlevel=99

" Change leader
let mapleader=","
let g:mapleader=","

" System wide clipboard
set clipboard=unnamed

" Quick save
nmap <leader>w :w!<cr>

" Key re-mappings
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
         
nnoremap <space> za

" Setup Vundle and plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')
   " Plugin manager
   Plugin 'gmarik/vundle'                         " plugin manager

   " Plugin libraries for plugins
   Plugin 'tomtom/tlib_vim'                       " provides utility functions
   Plugin 'mattn/webapi-vim'                      " webapi utility functions
   Plugin 'marcweber/vim-addon-mw-utils'          " interpret a file by function and cache

   " Search plugins
   Plugin 'mileszs/ack.vim'                       " quickly serah within vim
   Plugin 'wincent/command-t'                     " fast file navigation for vim
   Plugin 'ctrlpvim/ctrlp.vim'                    " fuzzy finder for vim
   Plugin 'sandeepcr529/buffet.vim'               " buffer list for switching and managing buffers

   " Programming tools
   Plugin 'vim-scripts/vorax'                     " use vim as an oracle client
   Plugin 'garbas/vim-snipmate'                   " snippet tool
   Plugin 'jalvesaq/vimcmdline'                   " send lines to interpreter

   " Tools for git
   Plugin 'tpope/vim-fugitive'                    " git wrapper for vim
   Plugin 'samoshkin/vim-mergetool'               " use vim to resolve merge conflicts

   " Language support plugins
   Plugin 'hashivim/vim-packer'                   " packer language support
   Plugin 'hashivim/vim-vagrant'                  " vagrantfile language support
   Plugin 'sheerun/vim-polyglot'                  " multiple language support
   Plugin 'python-mode/python-mode'               " use vim as a python IDE
   Plugin 'hanschen/vim-ipython-cell'             " run ipython on current line

   " Motion plugins
   Plugin 'wellle/targets.vim'                    " add vim text objects
   Plugin 'andymass/vim-matchup'                  " extends vim's % motion to language-specific words
   Plugin 'kana/vim-textobj-user'                 " create vim text objects
   Plugin 'easymotion/vim-easymotion'             " move faster around vim
   Plugin 'yuttie/comfortable-motion.vim'         " smooth scrolling
   Plugin 'christoomey/vim-tmux-navigator'        " motions for using tmux
   Plugin 'colinkennedy/vim-textobj-block-party'  " vim motions for python

   " Web applications plugins
   "Plugin 'paulkass/jira-vim'                    " use jira from vim
   Plugin 'mattn/gist-vim'                        " upload snippets to github
   Plugin 'mrtazz/simplenote.vim'                 " use simplenote from vim
      let g:SimplenoteUsername=$SIMPLENOTE_USERNAME
      let g:SimplenotePassword=$SIMPLENOTE_PASSWORD
   "Plugin 'neilagabriel/vim-geeknote'            " use geeknote from vim
   
   " Appearance plugins
   Plugin 'tadaa/vimade'                          " fades inactive biffers
   Plugin 'morhetz/gruvbox'                       " gruvbox theme for vim
   Plugin 'fweep/vim-tabber'                      " labeling and manipulating tabs
      set tabline=%!tabber#TabLine()
   "Plugin 'majutsushi/tagbar'                    " tags viewer
   Plugin 'vim-scripts/gundo'                     " visualize vim undo tree
   Plugin 'bling/vim-airline'                     " show status bar on vim
   Plugin 'mhinz/vim-startify'                    " show a start screen on vim
   Plugin 'myusuf3/numbers.vim'                   " show relative numbers
   Plugin 'liuchengxu/vista.vim'                  " tags viewer
   Plugin 'kshenoy/vim-signature'                 " add visual markers to the buffer
   Plugin 'rrethy/vim-illuminate'                 " automatically highlighting other uses of the current word
   Plugin 'neoclide/coc-highlight'                " current word highlighter
   Plugin 'airblade/vim-gitgutter'                " show git modifications
   "Plugin 'niklaas/lightline-gitdiff'            " show gitdiff on lightline
   Plugin 'vim-airline/vim-airline-themes'        " themes for vim-airline
      let g:airline_powerline_fonts=1             " enable powerline fonts
         let g:airline_theme='gruvbox'            " set airline theme to gruvbox
   Plugin 'scrooloose/nerdtree'                   " show navigation tree
      let NERDTreeIgnore=['\.pyc$', '\~$']        " ignore files
   Plugin 'flazz/vim-colorschemes'                " load vim colorschemes
   Plugin 'jistr/vim-nerdtree-tabs'               " use tabs in nerdtree
   Plugin 'ryanoasis/vim-webdevicons'             " use better icons in vim
   Plugin 'kien/rainbow_parentheses.vim'          " highlight parentheses
   Plugin 'nathanaelkane/vim-indent-guides'       " show indent guides
   Plugin 'tmux-plugins/vim-tmux-focus-events'    " terminal vim and tmux work better
   
   " Linter plugins
   Plugin 'w0rp/ale'                              " syntax checking and semantic errors
   Plugin 'ervandew/supertab'                     " autocomplete with tab
   "Plugin 'scrooloose/syntastic'                 " syntax checking for vim
   Plugin 'davidhalter/jedi-vim'                  " vim auto-completition
   Plugin 'valloric/youcompleteme'                " code-completition engine

   " Formatting plugins
   Plugin 'nvie/vim-flake8'                       " flake 8 style
      let g:SupertabDefaultCompletitionType='context'
   Plugin 'tmsvg/pear-tree'                       " close open brackets
   Plugin 'godlygeek/tabular'                     " text filtering and alignment 
   Plugin 'tpope/vim-surround'                    " sorround vim objects
   Plugin 'tmhedberg/simpylfold'                  " code folding for python
      let g:SimpylFold_docstring_preview=1
   Plugin 'scrooloose/nerdcommenter'              " comment lines
   Plugin 'tweekmonster/impsort.vim'              " sort python imports
   Plugin 'terryma/vim-multiple-cursors'          " use multiple cursors

call vundle#end()
filetype plugin indent on

" Appearance options
set t_Co=256
set ruler
set laststatus=2
set cursorline
set wildmenu
set background=dark

syntax on
colorscheme gruvbox
