" Do not use compatibility mode
set nocompatible
filetype off

" Use utf-8
set encoding=utf-8

" Enable mouse
set mouse=a

" Set line numbers
set number

" Better indent
set autoindent
set smartindent

" Better search
set ignorecase
set smartcase
set incsearch
set magic

" Set history to 1,000 commands
set history=1000 

" Fix backspace
set backspace=eol,start,indent

" No backups
set nobackup
set nowb
set noswapfile

" Tab behavior
set expandtab
set smarttab
set shiftwidth=3
set tabstop=3

" Never show mode
set noshowmode

" Change leader
let mapleader=","
let g:mapleader=","

" Quick save
nmap <leader>w :w!<cr>

" Setup Vundle and plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')
   Plugin 'gmarik/vundle'
   Plugin 'scrooloose/nerdtree'
   Plugin 'scrooloose/nerdcommenter'
   Plugin 'scrooloose/syntastic'
   Plugin 'tpope/vim-surround'
   Plugin 'tpope/vim-fugitive'
   Plugin 'wincent/command-t'
   Plugin 'majutsushi/tagbar'
   Plugin 'flazz/vim-colorschemes' 
   Plugin 'sjl/gundo'
   Plugin 'mattn/gist-vim'
   Plugin 'MarcWeber/vim-addon-mw-utils' 
   Plugin 'tomtom/tlib_vim'              
   Plugin 'garbas/vim-snipmate'
   Plugin 'ervandew/supertab'
      let g:SupertabDefaultCompletitionType='context'
   Plugin 'bling/vim-airline'
      let g:airline_powerline_fonts=0
      let g:airline_theme='kolor'
call vundle#end()
filetype plugin indent on

" Appearance options
set t_Co=256
set ruler
set laststatus=2
set cursorline
set wildmenu
syntax on
set background=dark
colorscheme xoria256

