" Do not use compatibility mode
set nocompatible
filetype off

" Use utf-8
set encoding=utf-8

" Enable mouse
set mouse=a

" Set line numbers
set number

" Better indent
set autoindent
set smartindent

" Better search
set ignorecase
set smartcase
set incsearch
set magic

" Set history to 2,048 commands
set history=2048

" Fix backspace
set backspace=eol,start,indent
set colorcolumn=79,80

" No backups
set nobackup
set nowb
set noswapfile

" Tab behavior
set expandtab
set smarttab
set shiftwidth=3
set tabstop=3

" Never show mode
set noshowmode

" Python folding
set foldmethod=indent
set foldlevel=99

" Change leader
let mapleader=","
let g:mapleader=","

" System wide clipboard
set clipboard=unnamed

" Quick save
nmap <leader>w :w!<cr>

" Key re-mappings
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
         
nnoremap <space> za

" Setup Vundle and plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')
   " Plugin manager
   Plugin 'gmarik/vundle' 
   Plugin 'scrooloose/nerdtree'
      let NERDTreeIgnore=['\.pyc$', '\~$'] " Ignore files
   Plugin 'scrooloose/nerdcommenter'
   "Plugin 'scrooloose/syntastic'
   Plugin 'jistr/vim-nerdtree-tabs'
   Plugin 'w0rp/ale'
   Plugin 'tpope/vim-surround'
   Plugin 'tpope/vim-fugitive'
   Plugin 'majutsushi/tagbar'
   Plugin 'flazz/vim-colorschemes' 
   Plugin 'vim-scripts/Gundo'
   Plugin 'mattn/gist-vim'
   Plugin 'mattn/webapi-vim'
   Plugin 'MarcWeber/vim-addon-mw-utils' 
   Plugin 'tomtom/tlib_vim'              
   Plugin 'garbas/vim-snipmate'
   "Plugin 'edkolev/tmuxline.vim'
   "Plugin 'neilagabriel/vim-geeknote'
   Plugin 'Lokaltog/vim-easymotion'
   Plugin 'godlygeek/tabular'
   Plugin 'plasticboy/vim-markdown'
   Plugin 'ctrlpvim/ctrlp.vim'
   "Plugin 'kien/ctrlp.vim'
   Plugin 'terryma/vim-multiple-cursors'
   Plugin 'vim-scripts/ag.vim'
   Plugin 'airblade/vim-gitgutter'
   Plugin 'myusuf3/numbers.vim'
   Plugin 'sandeepcr529/Buffet.vim'
   Plugin 'ervandew/supertab'
   Plugin 'nvie/vim-flake8'
      let g:SupertabDefaultCompletitionType='context'
   Plugin 'bling/vim-airline'
   Plugin 'morhetz/gruvbox'
   Plugin 'vim-airline/vim-airline-themes'
      let g:airline_powerline_fonts=1
         let g:airline_theme='gruvbox'
   Plugin 'tmux-plugins/vim-tmux-focus-events'
   Plugin 'ryanoasis/vim-webdevicons'
   Plugin 'fweep/vim-tabber'
      set tabline=%!tabber#TabLine()
   Plugin 'mhinz/vim-startify'
   Plugin 'nathanaelkane/vim-indent-guides'
   Plugin 'mrtazz/simplenote.vim'
      let g:SimplenoteUsername=$SIMPLENOTE_USERNAME
      let g:SimplenotePassword=$SIMPLENOTE_PASSWORD
   Plugin 'vim-scripts/vorax'

   " Syntax  higligting and language support 
   Plugin 'lervag/vimtex'
   Plugin 'ekalinin/Dockerfile.vim'
   Plugin 'hashivim/vim-packer'
   Plugin 'hashivim/vim-vagrant'
   Plugin 'hashivim/vim-terraform'
   Plugin 'pearofducks/ansible-vim'
   Plugin 'tmhedberg/SimpylFold'
      let g:SimpylFold_docstring_preview=1
   Plugin 'yuttie/comfortable-motion.vim'
   Plugin 'mileszs/ack.vim'
   Plugin 'kien/rainbow_parentheses.vim'
   Plugin 'davidhalter/jedi-vim'
   Plugin 'tweekmonster/impsort.vim'
   Plugin 'valloric/youcompleteme'
   Plugin 'python-mode/python-mode'
   Plugin 'wincent/command-t'
   Plugin 'liuchengxu/vista.vim'
   Plugin 'niklaas/lightline-gitdiff'
   Plugin 'samoshkin/vim-mergetool'
   Plugin 'paulkass/jira-vim'
   Plugin 'neoclide/coc-highlight'
   Plugin 'RRethy/vim-illuminate'
   Plugin 'TaDaa/vimade'
   Plugin 'andymass/vim-matchup'
   Plugin 'ColinKennedy/vim-textobj-block-party'
   Plugin 'kshenoy/vim-signature'
   Plugin 'tmsvg/pear-tree'
   Plugin 'christoomey/vim-tmux-navigator'
   Plugin 'wellle/targets.vim'
   Plugin 'jalvesaq/vimcmdline'
   Plugin 'hanschen/vim-ipython-cell'
   Plugin 'sheerun/vim-polyglot'

call vundle#end()
filetype plugin indent on

" Appearance options
set t_Co=256
set ruler
set laststatus=2
set cursorline
set wildmenu
set background=dark

syntax on
colorscheme gruvbox
