# encoding: utf-8
# -*- mode: ruby
# vi: set ft=ruby

Vagrant.configure(2) do |config|
   config.vm.box = 'ubuntu/disco64'
   config.vm.provider 'virtualbox' do |vb|
      vb.cpus   = 2 
      vb.name   = 'devbox'
      vb.memory = 4096
   end

   #config.ssh.username = 'hdtxn'
   #config.ssh.password = 'hdtxn'

   #config.vm.network 'fowardedport', guest: 80, host: 150
   #config.vm.synced_folder './vagrant', '/home/vagrant/'
   config.vm.hostname   = 'devbox'
   config.disksize.size = '80GB'

   config.vm.provision 'shell', inline: <<-SHELL
      apt-get update
      #apt-get upgrade -y
      apt-get install -y ansible
   SHELL

   config.vm.provision 'ansible_local' do |ansible|
      ansible.limit              = 'all,localhost'
      ansible.verbose            = 'vvv'
      ansible.playbook           = 'devbox-playbook.yml'
      ansible.install_mode       = 'default'
      ansible.compatibility_mode = 'auto'
   end
end
