source $HOME/.dotfiles/general/environment
source $HOME/.dotfiles/general/aliases
source $HOME/.dotfiles/zsh/antigen/antigen.zsh

export ANTIGEN_DEFAULT_REPO_URL=https://github.com/robbyrussell/oh-my-zsh

ZSH_TMUX_AUTOSTART=true

antigen-use oh-my-zsh

antigen-bundle git
antigen-bundle pip
antigen bundle tmux
antigen bundle fasd
antigen bundle sudo
antigen bundle pep8
antigen bundle python
antigen-bundle vi-mode
antigen-bundle autopep8
antigen bundle tmuxinator

antigen bundle chrissicool/zsh-256color
antigen bundle tarruda/zsh-autosuggestions
antigen bundle Tarrasch/zsh-colors
antigen bundle s7anley/zsh-geeknote
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme steeef
antigen-apply
