source $HOME/.dot/general/aliases
source $HOME/.dot/general/functions
source $HOME/.dot/general/environment
source /usr/share/zsh-antigen/antigen.zsh

eval "$(fasd --init auto)"
eval "$(thefuck --alias)"

# Bind UP and DOWN arrow keys to fix vi-mode and history-substring-search conflict
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

antigen-use oh-my-zsh
antigen bundle <<EOBUNDLES
   cp
   aws
   git
   gem
   pip
   npm
   #tmux
   sudo
   fasd
   sudo
   pep8
   rsync
   django
   debian
   httpie
   python
   docker
   extract
   history
   vi-mode
   colorize
   compleat
   autopep8
   bundle tmuxinator
   web-search
   rand-quote
   colored-man-pages
   history-substring-search

   zpm-zsh/dropbox
   Tarrasch/zsh-colors
   s7anley/zsh-geeknote
   willghatch/zsh-snippets
   chrissicool/zsh-256color
   tarruda/zsh-autosuggestions
   felixr/docker-zsh-completion
   zdharma/fast-syntax-highlighting
   #zsh-users/zsh-syntax-highlighting
   viasite-ansible/zsh-ansible-server
   EslamElHusseiny/aws_manager_plugin
   zsh-users/zsh-history-substring-search
EOBUNDLES

#antigen theme steeef
#antigen theme wesbos/Cobalt2-iterm cobalt2.zsh-theme
antigen theme bhilburn/powerlevel9k powerlevel9k.zsh-theme
#antigen theme caiogondim/bullet-train-oh-my-zsh-theme bullet-train

antigen apply
