# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Setup custom prompts
PS1='\[\033[01;32m\]\n┌[\d]-[\w]\n\[\033[00m\]\[\033[01;34m\]└─[\!]-[\j]-[\u@\h]\$\[\033[0;35m\] '
PS2='>'
PS3='>>'
PS4='>>>'

# If aliases file exists, load it
if [ -f $HOME/.bash_aliases ]; then
   source $HOME/.bash_aliases
fi
